apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters:
    - name: StringTest      
      value: replaceme
      label: String Field      
      BU_type: 
        type: String
        help: Put a String here
        preview: Please enter a string
        max: 5
        min: 1                 

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: StringTest
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.StringTest}}"]
