apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters:
    - name: message      
      value: hello world
      BU_type: 
        type: String
        max: 5
        min: 1
    - name: message2
      value: hello world
      BU_type: 
        type: Integer
        max: 5
        min: 2
    - name: message3      
      value: hello world
      BU_type: 
        type: String
        max: 20
        min: 2

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
