apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters:
    - name: StringTest      
      value: replaceme
      label: String Field
      BU_type: 
        type: String
        help: Put a String here
        max: 5
        min: 1
    - name: IntegerTest
      value: replaceme
      label: Integer Field
      BU_type: 
        type: Integer
        help: Put an Integer here        
        max: 5
        min: 2
    - name: DateTest      
      value: replaceme
      label: Date Field
      BU_type: 
        type: Date
        help: Put a Date here        
        max: '{"weeks":17, "days":12}' 
    - name: FloatTest      
      value: replaceme
      label: Float Field
      BU_type: 
        type: Float
        help: put a Float here
        max: 19.99
        min: 2  
#    - name: List String Test
#      value: replaceme
#      BU_type:
#        #definer type eller list???      
#        list: true
#        type: list
#        BU_type:
#            name: First in list
#            type: String
#            help: Put a string here
#            max: 15
#            min: 2
#        BU_type:
#            name: Second in list
#            type: String
#            help: Put a string here
#            max: 15
#            min: 2
#        BU_type:
#            name: Third in list
#            type: String
#            help: Put a string here
#            max: 15
#            min: 2            

                 

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: FloatTest
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.FloatTest}}"]
