apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: whalesay
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters:
    - name: String Test      
      value: replaceme
      BU_type: 
        type: String
        help: Put a String here
        max: 5
        min: 1
    - name: Integer Test
      value: replaceme
      BU_type: 
        type: Integer
        help: Put an Integer here        
        max: 5
        min: 2
    - name: Date Test      
      value: replaceme
      BU_type: 
        type: Date
        help: Put a Date here        
        max: months = 6, days = 12
    - name: DateTime Test      
      value: replaceme
      BU_type: 
        type: DateTime
        help: Put a DateTime here
        max: 20
        min: 2      
    - name: Float Test      
      value: replaceme
      BU_type: 
        type: Float
        helper: put a Float here
        max: 19.99
        min: 2


  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
